# Generated by Django 4.2.3 on 2024-10-25 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pongMulti', '0005_alter_matchhistory_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
