# Generated by Django 4.2.3 on 2024-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_gameinvitation_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
