# Generated by Django 4.2.3 on 2024-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dauth',
            field=models.BooleanField(default=False),
        ),
    ]
