# Generated by Django 4.2.3 on 2024-10-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_message_message'),
        ('users', '0030_user_dauth_user_otp_code_user_otp_created_at'),
    ]

    operations = [
    ]
