# Generated by Django 4.2.3 on 2024-11-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_sup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id42',
            field=models.IntegerField(default=None),
        ),
    ]
