# Generated by Django 4.2.3 on 2024-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_user_id42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id42',
            field=models.CharField(null=True),
        ),
    ]
