# Generated by Django 4.2.3 on 2024-11-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_id42'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id42',
        ),
    ]
