# Generated by Django 4.2.3 on 2024-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_user_id42'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myid42',
            field=models.CharField(default='Not42'),
        ),
    ]
