# Generated by Django 4.2.3 on 2024-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_gamesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='keyBind',
            field=models.CharField(default='w,s', verbose_name=models.CharField(max_length=10)),
        ),
    ]
