# Generated by Django 4.2.3 on 2024-11-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_gamesettings_keybind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='keyBind',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='down',
            field=models.CharField(default='s', verbose_name=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='up',
            field=models.CharField(default='w', verbose_name=models.CharField(max_length=10)),
        ),
    ]
