# Generated by Django 4.2.3 on 2024-11-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_gamesettings_keybind_gamesettings_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='ballSkin',
            field=models.CharField(default='default', max_length=125),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='boardSkin',
            field=models.CharField(default='default', max_length=125),
        ),
    ]
