# Generated by Django 4.2.3 on 2024-11-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_tournamentswin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournamentName',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
