# Generated by Django 4.2.3 on 2024-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_tournamentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tournamentName',
            field=models.CharField(max_length=15),
        ),
    ]
